version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=eivydas
      - MONGO_INITDB_ROOT_PASSWORD=eivydas1
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-db:/data/redis
volumes:
  mongo-db:
  redis-db:
